type WebficItem = {
  title: string
}

type Data = {
  [key: string]: WebficItem[]
}

// Raw mapping of years to arrays of titles
const rawData: Record<string, string[]> = {
  "≤2010": [
    "Harry Potter and the Methods of Rationality",
    "John Dies at the End",
    "The Legion of Nothing",
    "Super Powereds",
    "Homestuck",
    "Luminosity",
    "Fine Structure",
    "Dungeon Keeper Ami",
    "Three Worlds Collide",
    "The Metamorphosis of Prime Intellect",
    "Tales of Mu",
    "Saga of Soul",
  ],
  "2011-12": [
    "Worm",
    "The Martian",
    "Mother of Learning",
    "To the Stars",
    "Friendship Is Optimal",
    "The Last Angel",
    "Fallout: Equestria",
    "Harry Potter and the Natural 20",
    "Dreaming of Sunshine",
    "The New World",
    "Brennus",
    "The Game of Champions",
  ],
  "2013-14": [
    "Pact",
    "The Zombie Knight",
    "The Gods are Bastards",
    "With This Ring",
    "The Metropolitan Man",
    "City of Angles",
    "Ra",
    "Pokemon: The Origin of Species",
    "The Two Year Emperor",
    "Stone Burners",
    "Twisted Cogs",
    "Floornight",
  ],
  "2015": [
    "Twig",
    "A Practical Guide to Evil",
    "Reverend Insanity",
    "The Iron Teeth: A Goblin's Tale",
    "A Hero's War",
    "The Fifth Defiance",
    "The Northern Caves",
    "Void Domain",
    "The Waves Arisen",
    "Fargo",
    "Marked for Death",
    "Set In Stone",
  ],
  "2016": [
    "The Wandering Inn",
    "Savage Divinity",
    "Forty Millenniums of Cultivation",
    "Unsong",
    "Everybody Loves Large Chests",
    "Arcane Emperor",
    "How to Avoid Death on a Daily Basis",
    "Crystal Society",
    "Cordyceps",
    "The Eagle's Flight",
    "Shadows of the Limelight",
    "Almost Nowhere",
  ],
  "2017": [
    "Ward",
    "The Legend of Randidly Ghosthound",
    "Worth the Candle",
    "The World As It Appears To Be",
    "Ave Xia Rem Y",
    "Cultivation Chat Group",
    "17776",
    "Metaworld Chronicles",
    "Threadbare",
    "The Good Student",
    "Modern Cannibals",
    "The Erogamer",
  ],
  "2018": [
    "Omniscient Reader's Viewpoint",
    "RE: Trailer Trash",
    "Lord of the Mysteries",
    "Forge of Destiny",
    "There is no Epic Loot here, Only Puns",
    "The Daily Grind",
    "Super Minion",
    "Epilogue",
    "Into the Mire",
    "The Law of Averages",
    "The Gig Economy",
    "Dave Scum",
  ],
  "2019": [
    "Pale",
    "Chrysalis",
    "Delve",
    "Vainqueur the Dragon",
    "Katalepsis",
    "Blue Core",
    "He Who Fights With Monsters",
    "Azarinth Healer",
    "The Flower That Bloomed Nowhere",
    "Wake of the Ravager",
    "Ar'Kendrithyst",
    "Chili and the Chocolate Factory: Fudge Revelation",
  ],
  "2020": [
    "Dungeon Crawler Carl",
    "The Primal Hunter",
    "The Runesmith",
    "Stray Cat Strut",
    "The Perfect Run",
    "Borne of Caution",
    "Prophecy Approved Companion",
    "The Hedge Wizard",
    "Cinnamon Bun",
    "A Practical Guide to Sorcery",
    "Castle Kingside",
    "Never Die Twice",
  ],
  "2021": [
    "Beware of Chicken",
    "Vigor Mortis",
    "Virtuous Sons",
    "Peculiar Soul",
    "The Last Orellen",
    "Fox’s Tongue and Kirin’s Bone",
    "Kitty Cat Kill Sat",
    "12 Miles Below",
    "Jackal Among Snakes",
    "Only Villains Do That",
    "This Used to Be About Dungeons",
    "Planecrash",
  ],
  "2022": [
    "Pale Lights",
    "Paranoid Mage",
    "Necroepilogos",
    "Industrial Strength Magic",
    "Player Manager",
    "Time to Orbit: Unknown",
    "A Soldier's Life",
    "Ghost in the City",
    "Nowhere Stars",
    "The Type Specialist",
    "I Will Touch the Skies",
    "Thresholder",
  ],
  "2023": [
    "Super Supportive",
    "Zenith of Sorcery",
    "The Game at Carousel",
    "Chasing Sunlight",
    "Bog Standard Isekai",
    "Slumrat Rising",
    "Hoard",
    "Rock falls, everyone dies",
    "Sublight Drive",
    "Brainpunch",
    "Path of Dragons",
    "Chains of a Time Loop",
  ],
  "2024": [
    "Claw",
    "The Legend of William Oh",
    "Saving the school would have been easier as a cafeteria worker",
    "Seek",
    "The Years of Apocalypse",
    "Systema Delenda Est",
    "The Stubborn Skill-Grinder In A Time Loop",
    "Hohenfels",
    "Red Wishes Black Ink",
    "Sunspot",
    "Gunsoul",
    "When I Win the World Ends",
  ],
}

// Transform rawData into the desired Data shape
const data: Data = Object.fromEntries(
  Object.entries(rawData).map(([year, titles]) => [
    year,
    titles.map((title) => ({ title }))
  ])
) as Data

export const getWebficTitle = (webfic: WebficItem): string => {
  return webfic.title
}

export default data
