import type { WebficItem } from "../types"

export const works: WebficItem[] = [
  // ≤2010
  {
    title: "Harry Potter and the Methods of Rationality",
    year: 2010,
    order: 0,
    tags: ["yudkowsky"],
  },
  { title: "John Dies at the End", year: 2010, order: 1, tags: [] },
  { title: "The Legion of Nothing", year: 2010, order: 2, tags: [] },
  { title: "Super Powereds", year: 2010, order: 3, tags: [] },
  { title: "Homestuck", year: 2010, order: 4, tags: [] },
  { title: "Luminosity", year: 2010, order: 5, tags: [] },
  { title: "Fine Structure", year: 2010, order: 6, tags: [] },
  { title: "Dungeon Keeper Ami", year: 2010, order: 7, tags: [] },
  { title: "Three Worlds Collide", year: 2010, order: 8, tags: ["yudkowsky"] },
  {
    title: "The Metamorphosis of Prime Intellect",
    year: 2010,
    order: 9,
    tags: [],
  },
  { title: "Tales of Mu", year: 2010, order: 10, tags: [] },
  { title: "Saga of Soul", year: 2010, order: 11, tags: [] },

  // 2011-12
  { title: "Worm", year: 2011, order: 0, tags: ["wildbow"] },
  { title: "The Martian", year: 2011, order: 1, tags: [] },
  { title: "Mother of Learning", year: 2011, order: 2, tags: [] },
  { title: "To the Stars", year: 2011, order: 3, tags: [] },
  { title: "Friendship Is Optimal", year: 2011, order: 4, tags: [] },
  { title: "The Last Angel", year: 2011, order: 5, tags: [] },
  { title: "Fallout: Equestria", year: 2011, order: 6, tags: [] },
  { title: "Harry Potter and the Natural 20", year: 2011, order: 7, tags: [] },
  { title: "Dreaming of Sunshine", year: 2011, order: 8, tags: [] },
  { title: "The New World", year: 2011, order: 9, tags: [] },
  { title: "Brennus", year: 2011, order: 10, tags: [] },
  { title: "The Game of Champions", year: 2011, order: 11, tags: [] },

  // 2013-14
  { title: "Pact", year: 2013, order: 0, tags: ["wildbow"] },
  { title: "The Zombie Knight", year: 2013, order: 1, tags: [] },
  { title: "The Gods are Bastards", year: 2013, order: 2, tags: [] },
  { title: "With This Ring", year: 2013, order: 3, tags: [] },
  { title: "The Metropolitan Man", year: 2013, order: 4, tags: ["wales"] },
  { title: "City of Angles", year: 2013, order: 5, tags: [] },
  { title: "Ra", year: 2013, order: 6, tags: [] },
  { title: "Pokemon: The Origin of Species", year: 2013, order: 7, tags: [] },
  { title: "The Two Year Emperor", year: 2013, order: 8, tags: [] },
  { title: "Stone Burners", year: 2013, order: 9, tags: [] },
  { title: "Twisted Cogs", year: 2013, order: 10, tags: [] },
  { title: "Floornight", year: 2013, order: 11, tags: [] },

  // 2015
  { title: "Twig", year: 2015, order: 0, tags: ["wildbow"] },
  { title: "A Practical Guide to Evil", year: 2015, order: 1, tags: [] },
  { title: "Reverend Insanity", year: 2015, order: 2, tags: [] },
  { title: "The Iron Teeth: A Goblin's Tale", year: 2015, order: 3, tags: [] },
  { title: "A Hero's War", year: 2015, order: 4, tags: [] },
  { title: "The Fifth Defiance", year: 2015, order: 5, tags: [] },
  { title: "The Northern Caves", year: 2015, order: 6, tags: [] },
  { title: "Void Domain", year: 2015, order: 7, tags: [] },
  { title: "The Waves Arisen", year: 2015, order: 8, tags: [] },
  { title: "Fargo", year: 2015, order: 9, tags: ["bavitz"] },
  { title: "Marked for Death", year: 2015, order: 10, tags: [] },
  { title: "Set In Stone", year: 2015, order: 11, tags: [] },

  // 2016
  { title: "The Wandering Inn", year: 2016, order: 0, tags: [] },
  { title: "Savage Divinity", year: 2016, order: 1, tags: [] },
  { title: "Forty Millenniums of Cultivation", year: 2016, order: 2, tags: [] },
  { title: "Unsong", year: 2016, order: 3, tags: [] },
  { title: "Everybody Loves Large Chests", year: 2016, order: 4, tags: [] },
  { title: "Arcane Emperor", year: 2016, order: 5, tags: [] },
  {
    title: "How to Avoid Death on a Daily Basis",
    year: 2016,
    order: 6,
    tags: [],
  },
  { title: "Crystal Society", year: 2016, order: 7, tags: [] },
  { title: "Cordyceps", year: 2016, order: 8, tags: [] },
  { title: "The Eagle's Flight", year: 2016, order: 9, tags: [] },
  { title: "Shadows of the Limelight", year: 2016, order: 10, tags: ["wales"] },
  { title: "Almost Nowhere", year: 2016, order: 11, tags: [] },

  // 2017
  { title: "Ward", year: 2017, order: 0, tags: ["wildbow"] },
  {
    title: "The Legend of Randidly Ghosthound",
    year: 2017,
    order: 1,
    tags: [],
  },
  { title: "Worth the Candle", year: 2017, order: 2, tags: ["wales"] },
  { title: "The World As It Appears To Be", year: 2017, order: 3, tags: [] },
  { title: "Ave Xia Rem Y", year: 2017, order: 4, tags: [] },
  { title: "Cultivation Chat Group", year: 2017, order: 5, tags: [] },
  { title: "17776", year: 2017, order: 6, tags: [] },
  { title: "Metaworld Chronicles", year: 2017, order: 7, tags: [] },
  { title: "Threadbare", year: 2017, order: 8, tags: [] },
  { title: "The Good Student", year: 2017, order: 9, tags: [] },
  { title: "Modern Cannibals", year: 2017, order: 10, tags: ["bavitz"] },
  { title: "The Erogamer", year: 2017, order: 11, tags: [] },

  // 2018
  { title: "Omniscient Reader's Viewpoint", year: 2018, order: 0, tags: [] },
  { title: "RE: Trailer Trash", year: 2018, order: 1, tags: [] },
  { title: "Lord of the Mysteries", year: 2018, order: 2, tags: [] },
  { title: "Forge of Destiny", year: 2018, order: 3, tags: [] },
  {
    title: "There is no Epic Loot here, Only Puns",
    year: 2018,
    order: 4,
    tags: [],
  },
  { title: "The Daily Grind", year: 2018, order: 5, tags: [] },
  { title: "Super Minion", year: 2018, order: 6, tags: [] },
  { title: "Epilogue", year: 2018, order: 7, tags: [] },
  { title: "Into the Mire", year: 2018, order: 8, tags: [] },
  { title: "The Law of Averages", year: 2018, order: 9, tags: [] },
  { title: "The Gig Economy", year: 2018, order: 10, tags: [] },
  { title: "Dave Scum", year: 2018, order: 11, tags: [] },

  // 2019
  { title: "Pale", year: 2019, order: 0, tags: ["wildbow"] },
  { title: "Chrysalis", year: 2019, order: 1, tags: [] },
  { title: "Delve", year: 2019, order: 2, tags: [] },
  { title: "Vainqueur the Dragon", year: 2019, order: 3, tags: [] },
  { title: "Katalepsis", year: 2019, order: 4, tags: [] },
  { title: "Blue Core", year: 2019, order: 5, tags: [] },
  { title: "He Who Fights With Monsters", year: 2019, order: 6, tags: [] },
  { title: "Azarinth Healer", year: 2019, order: 7, tags: [] },
  { title: "The Flower That Bloomed Nowhere", year: 2019, order: 8, tags: [] },
  { title: "Wake of the Ravager", year: 2019, order: 9, tags: [] },
  { title: "Ar'Kendrithyst", year: 2019, order: 10, tags: [] },
  {
    title: "Chili and the Chocolate Factory: Fudge Revelation",
    year: 2019,
    order: 11,
    tags: [],
  },

  // 2020
  { title: "Dungeon Crawler Carl", year: 2020, order: 0, tags: [] },
  { title: "The Primal Hunter", year: 2020, order: 1, tags: [] },
  { title: "The Runesmith", year: 2020, order: 2, tags: [] },
  { title: "Stray Cat Strut", year: 2020, order: 3, tags: [] },
  { title: "The Perfect Run", year: 2020, order: 4, tags: [] },
  { title: "Borne of Caution", year: 2020, order: 5, tags: [] },
  { title: "Prophecy Approved Companion", year: 2020, order: 6, tags: [] },
  { title: "The Hedge Wizard", year: 2020, order: 7, tags: [] },
  { title: "Cinnamon Bun", year: 2020, order: 8, tags: [] },
  { title: "A Practical Guide to Sorcery", year: 2020, order: 9, tags: [] },
  { title: "Castle Kingside", year: 2020, order: 10, tags: [] },
  { title: "Never Die Twice", year: 2020, order: 11, tags: [] },

  // 2021
  { title: "Beware of Chicken", year: 2021, order: 0, tags: [] },
  { title: "Vigor Mortis", year: 2021, order: 1, tags: [] },
  { title: "Virtuous Sons", year: 2021, order: 2, tags: [] },
  { title: "Peculiar Soul", year: 2021, order: 3, tags: [] },
  { title: "The Last Orellen", year: 2021, order: 4, tags: [] },
  { title: "Fox’s Tongue and Kirin’s Bone", year: 2021, order: 5, tags: [] },
  { title: "Kitty Cat Kill Sat", year: 2021, order: 6, tags: [] },
  { title: "12 Miles Below", year: 2021, order: 7, tags: [] },
  { title: "Jackal Among Snakes", year: 2021, order: 8, tags: [] },
  { title: "Only Villains Do That", year: 2021, order: 9, tags: [] },
  {
    title: "This Used to Be About Dungeons",
    year: 2021,
    order: 10,
    tags: ["wales"],
  },
  { title: "Planecrash", year: 2021, order: 11, tags: ["yudkowsky"] },

  // 2022
  { title: "Pale Lights", year: 2022, order: 0, tags: [] },
  { title: "Paranoid Mage", year: 2022, order: 1, tags: [] },
  { title: "Necroepilogos", year: 2022, order: 2, tags: [] },
  { title: "Industrial Strength Magic", year: 2022, order: 3, tags: [] },
  { title: "Player Manager", year: 2022, order: 4, tags: [] },
  { title: "Time to Orbit: Unknown", year: 2022, order: 5, tags: [] },
  { title: "A Soldier's Life", year: 2022, order: 6, tags: [] },
  { title: "Ghost in the City", year: 2022, order: 7, tags: [] },
  { title: "Nowhere Stars", year: 2022, order: 8, tags: [] },
  { title: "The Type Specialist", year: 2022, order: 9, tags: [] },
  { title: "I Will Touch the Skies", year: 2022, order: 10, tags: [] },
  { title: "Thresholder", year: 2022, order: 11, tags: ["wales"] },

  // 2023
  { title: "Super Supportive", year: 2023, order: 0, tags: [] },
  { title: "Zenith of Sorcery", year: 2023, order: 1, tags: [] },
  { title: "The Game at Carousel", year: 2023, order: 2, tags: [] },
  { title: "Chasing Sunlight", year: 2023, order: 3, tags: [] },
  { title: "Bog Standard Isekai", year: 2023, order: 4, tags: [] },
  { title: "Slumrat Rising", year: 2023, order: 5, tags: [] },
  { title: "Hoard", year: 2023, order: 6, tags: [] },
  { title: "Rock falls, everyone dies", year: 2023, order: 7, tags: [] },
  { title: "Sublight Drive", year: 2023, order: 8, tags: [] },
  { title: "Brainpunch", year: 2023, order: 9, tags: [] },
  { title: "Path of Dragons", year: 2023, order: 10, tags: [] },
  { title: "Chains of a Time Loop", year: 2023, order: 11, tags: [] },

  // 2024
  { title: "Claw", year: 2024, order: 0, tags: ["wildbow"] },
  { title: "The Legend of William Oh", year: 2024, order: 1, tags: [] },
  {
    title: "Saving the school would have been easier as a cafeteria worker",
    year: 2024,
    order: 2,
    tags: [],
  },
  { title: "Seek", year: 2024, order: 3, tags: ["wildbow"] },
  { title: "The Years of Apocalypse", year: 2024, order: 4, tags: [] },
  { title: "Systema Delenda Est", year: 2024, order: 5, tags: [] },
  {
    title: "The Stubborn Skill-Grinder In A Time Loop",
    year: 2024,
    order: 6,
    tags: [],
  },
  { title: "Hohenfels", year: 2024, order: 7, tags: [] },
  { title: "Red Wishes Black Ink", year: 2024, order: 8, tags: [] },
  { title: "Sunspot", year: 2024, order: 9, tags: [] },
  { title: "Gunsoul", year: 2024, order: 10, tags: [] },
  {
    title: "When I Win the World Ends",
    year: 2024,
    order: 11,
    tags: ["bavitz"],
  },
]
